server:
context-path: /micro
port: 8080
spring:
datasource:
driverClassName: com.mysql.jdbc.Driver
url: jdbc:mysql://cap-sg-prd-4.securegateway.appdomain.cloud:19717/inventorydb
username: dbuser
password: Pass4dbUs3R
jpa:
database: MYSQL